services:
  backend:
    build: backend
    container_name: crud-backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URLS=${FRONTEND_URLS}
      - STORAGE_TABLE=${STORAGE_TABLE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  frontend:
    build: frontend
    container_name: crud-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}