name: Build new image and deploy to AWS Elastic Beanstalk

on:
  push:
    paths:
      - 'backend/**'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Required Secrets (Node.js)
        shell: node {0}
        run: |
          const required = [
            "AWS_ACCESS_KEY_ID",
            "AWS_DEFAULT_REGION",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_USER_ID",
            "ECR_REPOSITORY",
            "ELASTIC_BEANSTALK_APP_NAME",
            "ELASTIC_BEANSTALK_ENV_NAME"
          ];
          
          const secrets = JSON.parse(process.env.SECRETS_JSON);
          const missing = required.filter(key => !secrets[key]);
          
          if (missing.length > 0) {
            console.error("Missing Secrets:", missing.join(", "));
            process.exit(1);
          }
          console.log("All required secrets are present.");
        env:
          SECRETS_JSON: ${{ toJson(secrets) }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to AWS ECR
        id: build-image
        env:
          IMAGE_ADDR: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{  github.ref_name }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to Elastic Beanstalk.
          echo "image=$IMAGE_ADDR" >> $GITHUB_OUTPUT          
          docker build -t crud-backend:${{  github.ref_name }} .
          docker tag crud-backend:${{  github.ref_name }} $IMAGE_ADDR
          docker push $IMAGE_ADDR

      - name: AWS Elastic Beanstalk environment
        id: eb-env
        run: |
          cd ../housekeeping/elasticbeanstalk/
          zip -r ${{github.ref_name}}.zip Dockerrun.aws.json
          # Upload to S3
          aws s3 cp "${{github.ref_name}}.zip" s3://elasticbeanstalk-${{ secrets.AWS_DEFAULT_REGION }}-${{ secrets.AWS_USER_ID }}/${{ secrets.ELASTIC_BEANSTALK_APP_NAME }}/
          # Create App Version
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.ELASTIC_BEANSTALK_APP_NAME }} \
            --version-label "${{ github.ref_name }}-${{ github.sha }}" \
            --description "Deployed from ${{ github.ref_name }}" \
            --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_DEFAULT_REGION }}-${{ secrets.AWS_USER_ID }}",S3Key="${{ secrets.ELASTIC_BEANSTALK_APP_NAME }}/${{github.ref_name}}.zip"
          # Update Environment
          aws elasticbeanstalk update-environment \
            --application-name ${{ secrets.ELASTIC_BEANSTALK_APP_NAME }} \
            --environment-name ${{ secrets.ELASTIC_BEANSTALK_ENV_NAME }} \
            --version-label "${{ github.ref_name }}-${{ github.sha }}" \
          # Wait until it is updated
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ secrets.ELASTIC_BEANSTALK_APP_NAME }} \
            --environment-name ${{ secrets.ELASTIC_BEANSTALK_ENV_NAME }}
